### ISSUE TITLE
Building stream_unrar.cpp.o fails with error: expected initializer before ‘missing_file’

### ISSUE THREAD

**Issue by AndydeCleyre** [vlovich/stream-unrar#2]
Attempting to compile with gcc 4.8.0 raises an error as shown in the following output:

```
Scanning dependencies of target stream-unrar
[ 93%] Building CXX object CMakeFiles/stream-unrar.dir/stream_unrar.cpp.o
/.../stream_unrar.cpp:200:14: error: expected initializer before ‘missing_file’
 int CALLBACK missing_file(UINT msg, LPARAM UserData, LPARAM P1, LPARAM P2)
```

**Comment by vlovich** [comment]
Can't reproduce.  Tested w/ 4.8.4 on Linux & 7.1 on OSX without this error.  Maybe it had been fixed a while back or the configuration you used isn't specified sufficiently (OS, cmake version, etc) for me to reproduce.
